  
schema_version: v0.0.1

application:
  name: cloud-run-sample
  description: Sample cloud run application
  appConfig:
    version: 1
  artifacts:
    - name: Cloud_Run_Sample_Container_Image
      id: 5B98F69A-D349-4739-9652-1894B3110BBC
      containerImage:
        provider: custom_registry
        repo: gcr.io/vanguard-qa/cloudrun-server:latest
        reference: latest
  creds:
    - credsType_gcp
    - credsType_github