schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./app.yml

deployment:
  name: CloudRunDeployment
  description: Service Deployment
  deploymentConfig:
    artifact:
      id: 1DBE36B3-6C8C-4ED8-A57E-69C4D9D1C249
    provisioner: gcp
    template:
      moduleRefId: gcp:cloud-run@1
      inputs:
        region:  "us-central1"
        allowUnauthenticated:  true
    env:
      BUCKET: "${terraform.gcp_bucket.value}"
      PROJECT_ID: "vanguard-test-deploy"
      IMAGE_PATH: "test.gif"
    summary:
      - name: Service URL
        command: echo "gcloud run services describe cloud-run-sample --platform managed --region us-central1 --format 'value(status.url)'