schema_version: v0.0.1

application:
  name: app-runner
  description: Sample app runner demo application
  appConfig:
    version: 1
  artifacts:
    - name: AppRunnerSampleContainerImage
      id: 4FE1056C-E64F-46A3-8CA3-312AA19DE732
      containerImage:
        provider: public_elastic_container_registry
        repo: p0k3r4s4/runner-demo
        reference: latest
  creds:
    - credsType_aws
    - credsType_github