  
schema_version: v0.0.1

application:
  name: cloud-run
  description: Sample cloud run application
  appConfig:
    version: 1
  artifacts:
    - name: App_Runner_Sample_Container_Image
      id: 5B9AB086-222C-4CB4-BE8B-6B4F7ECE2223
      containerImage:
        provider: custom_registry
        repo: public.ecr.aws/p0k3r4s4/runner-demo
        reference: latest
  creds:
    - credsType_aws
    - credsType_github