schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./app.yml

deployment:
  name: AppRunnerDeployment
  description: Service Deployment
  deploymentConfig:
    artifact:
      id: 8529451B-76E0-4686-9C37-B27561425CB8
    provisioner: aws
    template:
      moduleRefId: aws:app-runner@1
      inputs:
        region:  "us-east-1"
        port: 8080
        role: "${terraform.aws_role.value}"
    env:
      BUCKET: "${terraform.aws_bucket.value}"
      REGION: "us-east-1"
      IMAGE_PATH: "test.gif"