schema_version: v0.0.1

application:
  name: cloud-run-wepdemo
  description: Sample cloud run application details
  appConfig:
    version: 1
  artifacts:
    - name: wordpress_container_image
      id: 1DAE9F95-1E68-462C-B075-05F462AA6B89
      containerImage:
        provider: custom_registry
        repo: wordpress
        reference: latest
  creds:
    - credsType_aws
    - credsType_github