schema_version: v0.0.1

environment:
  import: ./env.yml

application:
  import: ./app.yml

deployment:
  name: wordpressDeployment
  description: Wordpress Deployment
  deploymentConfig:
    artifact:
      id: 1DAE9F95-1E68-462C-B075-05F462AA6B89
    provisioner: gcp
    template:
      moduleRefId: gcp:cloud-run@1
      inputs:
        region:  "us-central1"
        allowUnauthenticated:  true
        port: 80
    env:
      WORDPRESS_DB_HOST: "${terraform.instance_ip_address.value}"
      WORDPRESS_DB_USER: "wpdemo"
      WORDPRESS_DB_PASSWORD: "f8zing4sxzpN1rDk"
      WORDPRESS_DB_NAME: "wpdb"
      WORDPRESS_DEBUG: "1"
      port: 80
    summary:
      - name: Service URL
        command: sleep 10 ; gcloud run services describe wpdemo --platform managed --region us-central1 --format 'value(status.url)'